import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";

import { OPTIONS_PROVIDER_READINESS_NOTE } from "@/components/admin/provider-health-panel";

const source = readFileSync(new URL("./provider-health-panel.tsx", import.meta.url), "utf8");

describe("provider health readiness copy", () => {
  it("keeps options/index provider guidance readiness-only", () => {
    expect(OPTIONS_PROVIDER_READINESS_NOTE).toContain("SPX/NDX may require index data access");
    expect(OPTIONS_PROVIDER_READINESS_NOTE).toContain("Indices Starter may be required if underlying index snapshots return not entitled");
    expect(OPTIONS_PROVIDER_READINESS_NOTE).toContain("does not silently substitute SPY/QQQ");
    expect(OPTIONS_PROVIDER_READINESS_NOTE).toContain("no SPY fallback is used");
    expect(OPTIONS_PROVIDER_READINESS_NOTE).toContain("explicit operator choice");
    expect(OPTIONS_PROVIDER_READINESS_NOTE).toContain("Options chain, IV, Greeks, open interest, and option snapshot marks depend on provider coverage");
    expect(OPTIONS_PROVIDER_READINESS_NOTE).toContain("mark_unavailable rather than fake P&L");
    expect(OPTIONS_PROVIDER_READINESS_NOTE).toContain("does not enable execution");
    expect(OPTIONS_PROVIDER_READINESS_NOTE.toLowerCase()).not.toContain("stage real order");
    expect(OPTIONS_PROVIDER_READINESS_NOTE.toLowerCase()).not.toContain("routing");
  });

  it("shows LLM provider health without exposing secret values", () => {
    expect(source).toContain("LLM provider");
    expect(source).toContain("LLM enabled");
    expect(source).toContain("key present");
    expect(source).toContain("fallback_reason");
    expect(source).toContain("last_error");
    expect(source).toContain("last_openai_error");
    expect(source).toContain("OpenAI status");
    expect(source).toContain("OpenAI request id");
    expect(source).toContain("config_state");
    expect(source).toContain("probe_state");
    expect(source).toContain("Probe not run");
    expect(source).toContain("Probe OK");
    expect(source).toContain("Probe warning");
    expect(source).toContain("Probe degraded");
    expect(source).toContain("Not entitled");
    expect(source).toContain("Underlying index unavailable");
    expect(source).toContain("Probe failed");
    expect(source).toContain("probe_llm=true");
    expect(source).toContain("sample option");
    expect(source).toContain("sample_underlying");
    expect(source).toContain("sample_option_symbol");
    expect(source).toContain("sample_selection_method");
    expect(source).toContain("sample method");
    expect(source).toContain("sample_mark_method");
    expect(source).toContain("mark method");
    expect(source).toContain("sample_expiration");
    expect(source).toContain("sample expiration");
    expect(source).toContain("sample_strike");
    expect(source).toContain("sample strike");
    expect(source).toContain("sample_option_type");
    expect(source).toContain("sample option type");
    expect(source).toContain("sample_dte");
    expect(source).toContain("sample DTE");
    expect(source).toContain("sample_has_bid_ask");
    expect(source).toContain("bid/ask exists");
    expect(source).toContain("sample_has_last_trade");
    expect(source).toContain("last trade exists");
    expect(source).toContain("sample_has_prior_close");
    expect(source).toContain("prior close exists");
    expect(source).toContain("sample_stale");
    expect(source).toContain("stale sample");
    expect(source).toContain("underlying_index_value_exists");
    expect(source).toContain("underlying index value");
    expect(source).toContain("entitlement_status");
    expect(source).toContain("entitlement status");
    expect(source).toContain("candidate_attempts");
    expect(source).toContain("candidate attempts");
    expect(source).toContain("sample symbol");
    expect(source).toContain("sample series");
    expect(source).toContain("indices_data");
    expect(source).toContain("indices data");
    expect(source).toContain("No index value");
    expect(source).toContain("index_samples");
    expect(source).toContain("index samples");
    expect(source).toContain("index value available");
    expect(source).toContain("credentials present");
    expect(source).toContain("paper routing enabled");
    expect(source).toContain("paper account status");
    expect(source).toContain("account probe");
    expect(source).toContain("order route probe");
    expect(source).toContain("entitlement_state");
    expect(source).toContain("Options marks unavailable");
    expect(source).toContain("index_options_data");
    expect(source).toContain("Index data entitlement required");
    expect(source).toContain("SPX index options discovered, but no fresh usable mark was returned for sampled contracts");
    expect(source).toContain("sample liquidity/freshness");
    expect(source).toContain("Indices Starter may be required");
    expect(source).toContain("No SPY fallback is used");
    expect(source).toContain("provider plan is not entitled");
    expect(source).toContain("Order routing is not enabled");
    expect(source).not.toContain("live probe:");
    expect(source).not.toContain("live probe: configured");
    expect(source).not.toContain("OPENAI_API_KEY");
    expect(source).not.toContain("sk-");
  });
});
