import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const source = readFileSync(new URL("./page.tsx", import.meta.url), "utf8");

describe("orders metric help rollout", () => {
  it("adds compact help to equity Orders P&L and fee labels without new actions", () => {
    expect(source).toContain('import { MetricLabel } from "@/components/ui/metric-help";');
    expect(source).toContain('<MetricLabel label="Realized net P&L" term="net_pnl" />');
    expect(source).toContain('<MetricLabel label="Fees" term="equity_commission_per_trade" />');
    expect(source).toContain('<MetricLabel label="Projected net outcome" term="net_pnl" />');
    expect(source).toContain('<MetricLabel label="Total fees" term="equity_commission_per_trade" />');
    expect(source).toContain('<MetricLabel label="gross P&L" term="gross_pnl" />');
    expect(source).toContain('<MetricLabel label="fees" term="equity_commission_per_trade" />');
    expect(source).toContain('<MetricLabel label="net P&L" term="net_pnl" />');
    expect(source).toContain("Recommended shares");
    expect(source).toContain("Order shares");
    expect(source).toContain("Estimated notional");
    expect(source).toContain("Max paper order value");
    expect(source).toContain("Max paper order value reduced");
    expect(source).toContain("Reset my paper portfolio");
    expect(source).toContain("Type RESET");
    expect(source).toContain("Calendar risk");
    expect(source).toContain("risk_calendar_confirmed");
    expect(source).toContain("risk_calendar_override_reason");
    expect(source).toContain("Confirmation reason");
    expect(source).toContain("Sit this one out");
    expect(source).toContain("Active Position Review");
    expect(source).toContain("/api/user/paper-positions/review");
    expect(source).toContain("Review only");
    expect(source).toContain("No automatic exits");
    expect(source).toContain("Paper position management");
    expect(source).toContain("current mark");
    expect(source).toContain("formatMarkAsOfTime(review.mark_as_of)");
    expect(source).toContain('<MetricLabel label="unrealized P&L" term="net_pnl" />');
    expect(source).toContain("stop / targets");
    expect(source).toContain("risk calendar");
    expect(source).toContain("Already open");
    expect(source).toContain("Review existing paper position");
    expect(source).toContain("Additional paper order would increase exposure");
    expect(source).toContain("Existing quantity");
    expect(source).toContain("New order quantity");
    expect(source).toContain("Combined quantity");
    expect(source).toContain("Combined estimated notional");
    expect(source).toContain('id="active-position-review"');
    expect(source).toContain("review_unavailable");
    expect(source).toContain("Options Position Review");
    expect(source).toContain("/api/user/options/paper-structures/review");
    expect(source).toContain("No automatic rolling");
    expect(source).toContain("No broker routing");
    expect(source).toContain("Mark unavailable");
    expect(source).toContain("Current estimated mark");
    expect(source).toContain("Net P&L");
    expect(source).toContain("Estimated total commissions");
    expect(source).toContain("Leg details");
    expect(source).toContain("method / source");
    expect(source).toContain("IV / OI");
    expect(source).toContain("Greeks");
    expect(source).toContain("Delta");
    expect(source).toContain("Gamma");
    expect(source).toContain("Theta");
    expect(source).toContain("Vega");
    expect(source).toContain("formatMaybeIv(leg.implied_volatility)");
    expect(source).toContain("formatOptionStructureToken(leg.mark_method)");
    expect(source).toContain("underlying_mark_price");
    expect(source).toContain("itm_otm_summary");
    expect(source).toContain("assignment_risk_summary");
    expect(source).toContain("exercise_risk_summary");
    expect(source).toContain("expiration_action_summary");
    expect(source).toContain("Paper-only settlement preview");
    expect(source).toContain("Paper-only settlement. No broker action.");
    expect(source).toContain("Settle paper expiration");
    expect(source).toContain("Type SETTLE");
    expect(source).toContain("moneyness");
    expect(source).toContain("assignment / exercise");
    expect(source).toContain("expiration_warning");
    expect(source).toContain("expired_unsettled");
    expect(source).toContain("settlement_available");
    expect(source).toContain("settlement_blocked_missing_underlying");
    expect(source).toContain("mark_unavailable");
    expect(source).toContain("Close position");
    expect(source).not.toContain("Auto close");
    expect(source).not.toContain("Scale in now");
    expect(source).not.toContain("Roll now");
    expect(source).not.toContain("Adjust now");
    expect(source).not.toContain("Auto roll");
    expect(source).not.toContain("Auto adjust");
    expect(source).not.toContain("Exercise now");
    expect(source).not.toContain("Assign now");
    expect(source).not.toContain("Send order");
    expect(source).not.toContain("live trading");
    expect(source).not.toContain("broker execution");
  });
});
